OrdererOrgs:
  - Name: Orderer
    Domain: fedshield.com
    EnableNodeOUs: false
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Org1
    Domain: org1.fedshield.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1