version: '3.7'

volumes:
  couchdb_data:

networks:
  fedshield:
    name: fedshield_network

services:
  # CouchDB for file storage
  couchdb:
    container_name: fedshield-couchdb
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - fedshield
    restart: unless-stopped